import { X, Sparkles, AlertCircle, RefreshCw } from 'lucide-react';

interface SummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summary?: string;
  isError?: boolean;
}

export function SummaryModal({ isOpen, onClose, summary, isError }: SummaryModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-6">
      <div className="relative w-full max-w-2xl">
        {/* Modal Card */}
        <div className="bg-gradient-to-b from-slate-950/95 to-blue-950/95 backdrop-blur-2xl rounded-3xl border border-white/20 shadow-2xl overflow-hidden">
          {/* Header */}
          <div className="relative p-6 border-b border-white/10">
            <div className="absolute inset-0 bg-gradient-to-r from-orange-600/20 to-teal-600/20" />
            <div className="relative flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-teal-400 to-blue-500 flex items-center justify-center shadow-lg">
                  {isError ? (
                    <AlertCircle className="w-6 h-6 text-white" />
                  ) : (
                    <Sparkles className="w-6 h-6 text-white" />
                  )}
                </div>
                <div>
                  <h2 className="text-xl font-bold text-white">
                    {isError ? 'AI Service Unavailable' : 'AI Thread Summary'}
                  </h2>
                  <p className="text-sm text-orange-300">
                    {isError ? 'Unable to generate summary' : 'Generated by Orbit AI'}
                  </p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 rounded-xl hover:bg-white/10 transition-colors"
              >
                <X className="w-5 h-5 text-orange-300" />
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="p-6">
            {isError ? (
              // Error State
              <div className="text-center py-8">
                <div className="w-24 h-24 mx-auto mb-6 rounded-3xl bg-gradient-to-br from-orange-500/20 to-red-500/20 border border-orange-400/30 flex items-center justify-center">
                  <div className="text-6xl">🤖</div>
                </div>
                <h3 className="text-2xl font-bold text-white mb-3">Oops! AI is Taking a Break</h3>
                <p className="text-orange-300 mb-6 max-w-md mx-auto">
                  Orbit AI is currently unavailable. It might be off exploring the digital cosmos
                  or simply needs a quick reboot. Please try again in a moment!
                </p>
                <button
                  onClick={onClose}
                  className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-orange-500 to-red-500 text-white font-semibold rounded-xl hover:shadow-lg hover:shadow-orange-500/30 transition-all"
                >
                  <RefreshCw className="w-4 h-4" />
                  <span>Try Again Later</span>
                </button>
              </div>
            ) : (
              // Success State
              <div className="bg-white/5 backdrop-blur-sm rounded-2xl p-6 border border-white/10">
                <div className="prose prose-invert max-w-none">
                  <p className="text-orange-200 leading-relaxed">
                    {summary ||
                      'The conversation thread discussed implementing a new chat feature with end-to-end encryption. Team members Sarah and Mike agreed on the technical approach, while Emma provided design feedback. The AI assistant suggested using WebSocket for real-time communication and recommended best practices for implementing E2EE in the browser.'}
                  </p>
                </div>

                {/* Key Points */}
                <div className="mt-6 space-y-3">
                  <h4 className="text-sm font-semibold text-orange-300 uppercase tracking-wider">
                    Key Highlights
                  </h4>
                  <div className="space-y-2">
                    {[
                      'E2EE implementation discussed',
                      'WebSocket for real-time messaging',
                      'Design feedback incorporated',
                      'Security best practices reviewed',
                    ].map((point, index) => (
                      <div
                        key={index}
                        className="flex items-center gap-3 p-3 bg-teal-500/10 rounded-xl border border-teal-400/20"
                      >
                        <div className="w-6 h-6 rounded-lg bg-gradient-to-br from-teal-400 to-blue-500 flex items-center justify-center flex-shrink-0">
                          <span className="text-white text-xs font-bold">{index + 1}</span>
                        </div>
                        <span className="text-orange-200 text-sm">{point}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Footer */}
          {!isError && (
            <div className="p-6 border-t border-white/10 bg-gradient-to-r from-slate-950/50 to-teal-950/50">
              <div className="flex items-center justify-between text-xs text-orange-300">
                <span>Powered by Orbit AI</span>
                <span>{new Date().toLocaleString()}</span>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
